# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  release:
    docker:
      # specify the version
      - image: circleci/golang:1.15
    environment:
      CI_SCRIPTS_CONFIG: ./.circleci/ci_scripts.yml
      GITHUB_RELEASE_TAG: latest
      CGO_ENABLED: 0

    steps:
      - checkout
      - run:
          name: Install ci-scripts
          command: wget -O - https://raw.githubusercontent.com/bcaldwell/ci-scripts/master/scripts/install.sh | bash
      - run: ci-scripts go/build
      - run: ci-scripts github/release

  release-docker:
    docker:
      - image: benjamincaldwell/ci-scripts

    working_directory: /go/src/github.com/bcaldwell/kube-deploy

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and pushing docker image
          command: ci-scripts docker/build_and_push_image --docker-images-dockerRepo benjamincaldwell/kube-deploy

workflows:
  version: 2
  release:
    jobs:
      - release
      - release-docker
