version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:1.15
    environment:
      CI_SCRIPTS_CONFIG: ./.circleci/ci_scripts.yml
      GITHUB_RELEASE_TAG: latest
      CGO_ENABLED: 0

    steps:
      - checkout

      - run:
          name: Install ci-scripts
          command: wget -O - https://raw.githubusercontent.com/bcaldwell/ci-scripts/master/scripts/install.sh | bash

      - run: ci-scripts go/build
      - run: ci-scripts github/release

  release-docker:
    docker:
      - image: benjamincaldwell/ci-scripts
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and pushing docker image
          command: ci-scripts docker/build_and_push_image --docker-images-dockerRepo benjamincaldwell/kube-deploy

workflows:
  version: 2
  release:
    jobs:
      - release:
          context:
            - github
      - release-docker:
          context:
            - docker
